apiVersion:       apps/v1
kind:             Deployment
metadata:
  name:           unhappy
spec:
  replicas:       1
  selector: 
    matchLabels:
      app: nevermind
  template:
    metadata:
      labels:
        app:      nevermind
    spec:
      containers:
      - name:     shell
        image:    busybox
        command:
        - "sh"
        - "-c"
        - "echo I will just print something here and then exit"
