apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functions.example.com
spec:
  group: example.com
  versions:
    - name: v1
      storage: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: 
              type: object
              properties:
                code: 
                  type: string
                ram: 
                  type: string
  scope: Namespaced
  names:
    kind: Function
    plural: functions
